name: Integration

on: push

jobs:
  static-test:
    name: Static Test

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.14.0']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.1.3

      - name: Setup Node.js (${{ matrix.node }}) environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Lint
        run: pnpm run lint

      - name: Format
        run: pnpm run format-check
